In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/Users/jomachase/Documents/Ironhack/Miniproject/MiniProject4/first_project/data/raw/winners_berlin_2020_2024.csv", low_memory=False)
df

   Year Gender              Winner   Country     Time
0  2020      M  No race (COVID-19)       NaN      NaN
1  2020      F  No race (COVID-19)       NaN      NaN
2  2021      M          Guye Adola  Ethiopia  2:05:45
3  2021      F  Gotytom Gebreslase  Ethiopia  2:20:09
4  2022      M      Eliud Kipchoge     Kenya  2:01:09
5  2022      F       Tigist Assefa  Ethiopia  2:15:37
6  2023      M      Eliud Kipchoge     Kenya  2:02:42
7  2023      F       Tigist Assefa  Ethiopia  2:11:53
8  2024      M      Eliud Kipchoge     Kenya  2:02:12
9  2024      F        Tigst Assefa  Ethiopia  2:13:44